# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('telefon', models.CharField(default='', max_length=15)),
                ('newsletter', models.BooleanField(default=False)),
                ('is_active_account', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
