# -*- coding: utf-8 -*-
# Generated by Django 1.10.1a1 on 2016-08-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'db_table': 'categories',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(help_text='Valeur de la couleur     en hexadecimal', max_length=7)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ModelNumber',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('size', models.CharField(blank=True, choices=[('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 40), ('42', 42), ('43', 43), ('44', 44), ('45', 45)], max_length=5, null=True)),
                ('material', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('HOMME', 'H'), ('FEMME', 'F')], max_length=6, null=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('coupon', models.PositiveIntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, choices=[('tags/product_phablet_options.html', 'Phablet'), ('tags/product_parfum_options.html', 'Parfum')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ProductType',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Product')),
                ('capacity', models.IntegerField(choices=[(1, '1ml'), (2, '2ml'), (10, '10ml'), (20, '20ml'), (30, '30ml'), (40, '40ml'), (50, '50ml'), (60, '60ml'), (70, '70ml'), (80, '80ml'), (90, '90ml'), (100, '100ml'), (110, '110ml'), (150, '150ml'), (200, '200ml')], default=100)),
                ('typ', models.CharField(choices=[('EDP', 'Eau de Parfum'), ('EDT', 'Eau de Toilette'), ('Cologne', 'Eau de Cologne'), ('Set', 'Coffret')], default='EDP', max_length=10)),
            ],
            options={
                'db_table': 'parfums',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Phablet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Product')),
                ('screen', models.FloatField(choices=[(4, '4"'), (4.5, '4.5"'), (4.7, '4.7"'), (5, '5"'), (5.1, '5.1"'), (5.2, '5.2"'), (5.5, '5.5"'), (5.7, '5.7"'), (6, '6'), (7, '7"'), (8, '8"'), (10, '10"')], default=5)),
                ('rear_camera', models.IntegerField(blank=True, choices=[(2, '2MP'), (5, '5MP'), (8, '8MP'), (10, '10MP'), (13, '13MP'), (16, '16MP'), (20, '20MP'), (21, '21MP')], default=13, null=True)),
                ('front_camera', models.IntegerField(blank=True, choices=[(2, '2MP'), (5, '5MP'), (8, '8MP'), (10, '10MP'), (13, '13MP'), (16, '16MP'), (20, '20MP'), (21, '21MP')], default=5, null=True)),
                ('system', models.CharField(max_length=512)),
                ('memory', models.IntegerField(choices=[(8, '8GB'), (16, '16GB'), (32, '32GB'), (64, '64GB'), (128, '128GB')], default=16)),
                ('ram_memory', models.IntegerField(choices=[(1, '1GB'), (2, '2GB'), (3, '3GB'), (4, '4GB'), (8, '8GB')], default=1)),
                ('extern_sdcard', models.BooleanField(default=False)),
                ('sim_card', models.CharField(choices=[('NO SIM', 'NO SIM'), ('STANDARD', 'STANDARD'), ('DUAL SIM', 'DUAL SIM'), ('TRIO SIM', 'TRIO SIM')], default='STANDARD', max_length=15)),
                ('battery', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'phones',
            },
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='catalog.ModelNumber'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='catalog.ProductType'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
