# -*- coding: utf-8 -*-
# Generated by Django 1.10.1a1 on 2016-08-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(help_text='Valeur de la couleur     en hexadecimal', max_length=7)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('related_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('material', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 40), ('42', 42), ('43', 43), ('44', 44), ('45', 45)], default='M', max_length=5)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Color')),
            ],
            options={
                'db_table': 'bags',
            },
        ),
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('related_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('capacity', models.IntegerField(choices=[(1, '1ml'), (2, '2ml'), (10, '10ml'), (20, '20ml'), (30, '30ml'), (40, '40ml'), (50, '50ml'), (60, '60ml'), (70, '70ml'), (80, '80ml'), (90, '90ml'), (100, '100ml'), (110, '110ml'), (150, '150ml'), (200, '200ml')], default=100)),
                ('typ', models.CharField(choices=[('EDP', 'Eau de Parfum'), ('EDT', 'Eau de Toilette'), ('Cologne', 'Eau de Cologne'), ('Set', 'Coffret')], default='EDP', max_length=10)),
                ('gender', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='F', max_length=10)),
            ],
            options={
                'db_table': 'parfums',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('related_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('screen', models.FloatField(choices=[(4, '4"'), (4.5, '4.5"'), (4.7, '4.7"'), (5, '5"'), (5.1, '5.1"'), (5.2, '5.2"'), (5.5, '5.5"'), (5.7, '5.7"'), (6, '6'), (7, '7"'), (8, '8"'), (10, '10"')], default=5)),
                ('camera', models.IntegerField(choices=[(2, '2MP'), (5, '5MP'), (8, '8MP'), (10, '10MP'), (13, '13MP'), (16, '16MP'), (20, '20MP'), (21, '21MP')], default=13)),
                ('system', models.CharField(max_length=512)),
                ('memory', models.IntegerField(choices=[(8, '8GB'), (16, '16GB'), (32, '32GB'), (64, '64GB'), (128, '128GB')], default=16)),
                ('sim_card', models.IntegerField(choices=[(1, 'STANDARD'), (2, 'DUAL SIM'), (3, 'TRIO SIM')], default=1)),
                ('battery', models.CharField(max_length=128)),
                ('frequency_band', models.CharField(max_length=512)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Color')),
            ],
            options={
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('related_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('material', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 40), ('42', 42), ('43', 43), ('44', 44), ('45', 45)], default='38', max_length=5)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Color')),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
