# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(help_text='Texte unique                            representant la page du produit.', max_length=255, unique=True)),
                ('parent_category', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='Liste de mot clés,                                     séparés par une virgule,                                     utilisés pour la recherche', max_length=255)),
                ('meta_description', models.CharField(help_text='Description                                        de mot clés', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(help_text='Valeur de la couleur     en hexadecimal', max_length=7)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'db_table': 'sizes',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('material', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bags',
                'ordering': ['-created_at'],
            },
            bases=('catalog.baseproduct',),
        ),
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('capacity', models.IntegerField()),
                ('typ', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'parfums',
                'ordering': ['-created_at'],
            },
            bases=('catalog.baseproduct',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('screen', models.CharField(max_length=512)),
                ('camera', models.CharField(max_length=512)),
                ('system', models.CharField(max_length=512)),
                ('memory', models.CharField(max_length=512)),
                ('sim_card', models.CharField(max_length=512)),
                ('battery', models.CharField(max_length=128)),
                ('frequency_band', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'phones',
                'ordering': ['-created_at'],
            },
            bases=('catalog.baseproduct',),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.BaseProduct')),
                ('material', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'shoes',
                'ordering': ['-created_at'],
            },
            bases=('catalog.baseproduct',),
        ),
        migrations.AddField(
            model_name='size',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BaseProduct'),
        ),
        migrations.AddField(
            model_name='color',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BaseProduct'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
