# -*- coding: utf-8 -*-
# Generated by Django 1.10.1a1 on 2016-08-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160827_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
