# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phablet',
            name='ram_memory',
            field=models.IntegerField(choices=[(512, '512MB'), (1, '1GB'), (2, '2GB'), (3, '3GB'), (4, '4GB'), (8, '8GB')], default=1),
        ),
        migrations.AlterField(
            model_name='phablet',
            name='screen',
            field=models.FloatField(choices=[(3.5, '3.5"'), (4, '4"'), (4.5, '4.5"'), (4.7, '4.7"'), (5, '5"'), (5.1, '5.1"'), (5.2, '5.2"'), (5.5, '5.5"'), (5.7, '5.7"'), (6, '6'), (7, '7"'), (8, '8"'), (10, '10"')], default=5),
        ),
    ]
